<form action="updatesorder" method="POST">
    <div class="form-group">
        <label class="col-md-4 control-label" for="id">ID</label>
        <div class="col-md-4">
            <input id="product_id" name="idn" placeholder="PRODUCT ID"
             class="form-control input-md" value=<?php echo $data[0]['id'] ?> required="" type="number">

        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label" for="product_id">PRODUCT_ID</label>
        <div class="col-md-4">
            <input id="product_id" name="id" placeholder="PRODUCT ID"
             class="form-control input-md" value=<?php echo $data[0]['product_id'] ?> required="" type="number">

        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label" for="user-id">USER_ID</label>
        <div class="col-md-4">
            <input id="product_name" name="name" placeholder="PRODUCT NAME"
             class="form-control input-md" value=<?php echo $data[0]['user_id'] ?> required="" type="text">

        </div>
    </div>

    <div class="form-group">
        <label class="col-md-4 control-label" for="available_quantity">QUANTITY</label>
        <div class="col-md-4">
            <input id="available_quantity" name="quantity" placeholder="AVAILABLE QUANTITY"
             class="form-control input-md" value=<?php echo $data[0]['quantity'] ?> required="" type="number">

        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label" for="status">Status</label>
        <div class="col-md-4">
            <label for="status">Change Status:</label>

            <select name="st" id="status">
                <option value="deliverd">Delivered</option>
                <option value="not delievered">not delivered</option>
                <option value="inprocess">In process</option>
            </select>

        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label" for="singlebutton">UPDATE Order</label>
        <div class="col-md-4">
            <button id="singlebutton" name="singlebutton" class="btn btn-primary">UPDATE</button>
        </div>
    </div>
</form>