<?php

echo $this->tag->linkTo(["signup","Signup Here","class"=>"btn btn-danger m-2"]);
echo $this->tag->linkTo(["login","LOgin Here","class"=>"btn btn-danger m-2"]);
echo $this->tag->linkTo(["signup","Signup Here","class"=>"btn btn-danger m-2"]);
echo $this->tag->linkTo(["logout","Logout Here","class"=>"btn btn-danger m-2"]);
echo $this->tag->linkTo(["setting","Setting Here","class"=>"btn btn-danger m-2"]);


echo "<section style='background-color: #eee;'><h2>Product Page<div class='container py-5'>
<div class='row'>";
foreach ($data as $key => $value) {
        echo "<div class='col-md-12 col-lg-4 mb-4 mb-lg-0'>
        <div class='card text-black'>
        <img src='".$value['image']."'class='card-img-top' alt='".$value['name']."' />
        <div class='card-body'><div class='text-center mt-1'><h4 class='card-title'>$value[name]</h4>
        <h6 class='text-primary mb-1 pb-3'>$ $value[price]</h6></div>";
     echo $this->tag->linkTo(["order/buynow?id=".$value['id'],"Buy Now!","class"=>"btn btn-danger"]);
       echo "
        </div></div></div>";
    }
echo "</div></div></section>";


