<?php

foreach ($data as $key => $value) {
    echo "
<div class='row'>
<div class='col-lg-18 border p-3 main-section bg-white'>
<div class='row hedding m-0 pl-3 pt-0 pb-3'>
<h3>ORDERS</h3>
<div class='row m-0'>
<div class='col-lg-10 left-side-product-box pb-3'>
<img src='" . $value['image'] . "' class='border p-3'>
</div>
<div class='col-lg-8'>
<div class='right-side-pro-detail border p-3 m-0'>
<div class='row'>
<div class='col-lg-12'>

<p class='m-0 p-0'>NAME OF THE PRODUCT : $value[name]</p>
</div>
<div class='col-lg-12'>
<p class='m-0 p-0 price-pro'>TOTAL PRICE -$$value[price]</p>
<hr class='p-0 m-0'>
</div>
<div class='col-lg-12'>
<h6>Quantity :</h6>
<input type='number' disabled class='form-control text-center w-100' value='1'>
</div>
<div class='col-lg-12 mt-3'>
<div class='row'>";
echo  $this->tag->linkTo(["product","Thank You","class"=>"btn btn-success w-100"]);

    echo "
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>";
}
