<?php

echo $this->tag->linkTo(["signup","Signup Here","class"=>"btn btn-danger m-2"]);
echo $this->tag->linkTo(["login","LOgin Here","class"=>"btn btn-danger m-2"]);
echo $this->tag->linkTo(["signup","Signup Here","class"=>"btn btn-danger m-2"]);
echo $this->tag->linkTo(["logout","Logout Here","class"=>"btn btn-danger m-2"]);


?>
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">ADMIN FEEDBACK</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">ADMIN WORK</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>